### ISSUE TITLE
empty repo

### ISSUE THREAD

**Issue by robo-alex** [Ainaz99/omnidata-annotator#2]
Thanks for your contributions!

Here I have some issues. When I finished the installation process, I found the 'annotator' and 'model' directories are empty. Could you please help me with that? Thanks!

**Comment by Ainaz99** [comment]
Hi @mtzhang1999!

Have you run the following command?

```
docker run -ti --rm -v PATH_TO_ANNOTATOR:/annotator -v PATH_TO_3D_MODEL:/model ainaz99/omnidata-annotator:latest
```

This should mount the annotator and the model to the `/annotator` and `/model` directories inside the docker container.
